#server:
#  port: 8104
#  servlet:
#    context-path: /business
#spring:
#  application:
#    name: business-server
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9100/eureka/
##seata客户端配置
#seata:
#  enabled: true
#  application-id: ccxi-abc
#  tx-service-group: ccxi_tx_group
#  service:
#    vgroup-mapping:
#      ccxi_tx_group: default
#  registry:
#    type: eureka
#    eureka:
#      service-url: http://localhost:9100/eureka/
#      application: default
#      weight: 1